services:
  db:
    image: postgres:17-alpine
    ports:
      - "4500:4500"
    environment:
      POSTGRES_USER: course
      POSTGRES_PASSWORD: course
      POSTGRES_DB: course_platform
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
