services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: course
      POSTGRES_PASSWORD: course
      POSTGRES_DB: course_platform
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
